services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
      - "./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:rw"
    ports:
      - "5433:5432"
    networks:
      - ny_taxi_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
    networks:
      - ny_taxi_network

networks:
  ny_taxi_network:
    driver: bridge
